Fix: Rewrite for non-localhost
MaritzSTL/mtz-ajax-interceptor pull request #12
Opened 2017-08-30 20:01 UTC by stramel

- `replacement` didn't handle `String`s properly when labelled as `Object`
     - Split it apart into `replacer` as a `Function` and `replacement` as a `String`
- `__host` was just the host and thus missing `protocol`
    - Switch to use `location.origin` which includes the `protocol`
- Fallback to `origin` if `baseUrl` and `localBaseUrl` are not defined.

2017-08-30 20:15 UTC, haydenmcp submitted a review, later dismissed

2017-09-01 13:59 UTC, admwx7 requested changes

2017-09-01 13:59 UTC, admwx7 commented on mtz-url-rewrite-interceptor.html
> +        /* Used in `String.replace` as the replacement `String` if replacer `Function` was not passed */
Are these comments backwards?  Or maybe the prop types?

2017-09-01 15:06 UTC, admwx7 approved these changes

2017-09-01 15:06 UTC, merged