New: setRequestHeader
MaritzSTL/mtz-ajax-interceptor pull request #13
Opened 2017-09-07 06:36 UTC by stramel

Allow handling of XHR `setRequestHeader`.

Do we want to handle the `setRequestHeader` automatically if it exists on the path?

**TODO:**

- [ ] Tests

2017-09-07 14:54 UTC, haydenmcp approved these changes

2017-09-07 20:35 UTC, admwx7 approved these changes

2017-09-07 20:35 UTC, admwx7 commented
LGTM just needs tests

2017-09-07 20:35 UTC, admwx7 requested changes
Unit tests

2017-09-07 20:36 UTC, haydenmcp submitted a review, later dismissed

2017-09-09 16:10 UTC, haydenmcp approved these changes

2017-09-11 16:01 UTC, admwx7 approved these changes

2017-09-11 16:02 UTC, merged